export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_ITEM_DELETE = "CART_ITEM_DELETE";
export const CART_SAVE_SHOPPING_ADDRESS = "CART_SAVE_SHOPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_EMPTY = "CART_EMPTY";
